---
- name: INSTALL PYTHON, DOCKER, DOCKER-COMPOSE and STARTED
  hosts: aws_ec2
  become: yes
  gather_facts: False
  tasks:
    - name: docker present
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - docker
          - python
          - python3-pip
        update_cache: yes
        state: present
    - name: docker-compose downloaded and installed
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
