---
- name: INSTALL DOCKER, DOCKER-COMPOSE and STARTED
  hosts: aws_ec2
  become: yes
  gather_facts: False
  tasks:
    - name: docker present
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - docker
          - python3
        update_cache: yes
        state: present
    - name: docker-compose downloaded and installed
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: python for docker installed
      pip:
        name:
          - docker
          - docker-compose
    - name: Docker service started
      service:
        name: docker
        state: started
    - name: ec2-user permission to run docker added
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: server connection reset
      meta: reset_connection
